# Modelling league dash data

In [1]:
import pickle
import pandas as pd
from pathlib import Path

In [2]:
fp = Path("../data/leagedash_merge_2018-19.pkl")
with open(fp, "rb") as f:
    df = pickle.load(f)

df.sample(6)

,PLAYER_NAME,TEAM_ABBREVIATION,AGE,GP,MIN,FG3M,FG3A,FTM,FTA,OREB,...,TOV_merge,STL_merge,BLK_merge,BLKA_merge,PF_merge,PFD_merge,PTS_merge,PLUS_MINUS_merge,FG2M_merge,FG2A_merge
PLAYER_ID,,,,,,,,,,,,,,,,,,,,,
202711,Bojan Bogdanovic,IND,30.0,81,2573.058333,2.3,5.4,3.4,4.3,0.5,...,1.864045,1.089888,0.0,1.2,1.882022,3.37191,20.057303,1.592135,4.946067,9.362921

In [4]:
fp = Path("../data/leagedash_merge_2004-05.pkl")
with open(fp, "rb") as f:
    det = pickle.load(f)

det.sample(5)

,PLAYER_NAME,TEAM_ABBREVIATION,AGE,GP,MIN,FG3M,FG3A,FTM,FTA,OREB,...,TOV_merge,STL_merge,BLK_merge,BLKA_merge,PF_merge,PFD_merge,PTS_merge,PLUS_MINUS_merge,FG2M_merge,FG2A_merge
PLAYER_ID,,,,,,,,,,,,,,,,,,,,,
1498,Antonio Daniels,SEA,30.0,75,2025.941667,0.9,2.9,4.4,5.4,0.4,...,1.354639,0.968041,0.07732,0.431959,1.400,0.0,15.362887,2.339175,4.090722,8.336082
951,Ray Allen,SEA,29.0,78,3068.548333,2.5,6.5,4.4,5.0,0.9,...,2.176000,1.044000,0.14400,0.756000,1.956,0.0,22.384000,2.452000,5.176000,11.000000
2412,Jiri Welsch,CLE,25.0,71,1320.661667,0.9,3.0,3.5,4.6,0.7,...,2.000000,1.200000,0.10000,0.400000,3.300,0.0,12.600000,-1.700000,3.200000,7.100000
2553,Jarvis Hayes,WAS,23.0,54,1562.715000,1.0,2.8,2.3,2.7,0.9,...,1.400000,1.100000,0.20000,0.500000,2.500,0.0,12.700000,-1.700000,3.700000,9.400000
2098,Slava Medvedenko,LAL,26.0,43,421.011667,0.0,0.1,2.0,2.4,2.7,...,1.100000,0.800000,0.20000,0.300000,5.500,0.0,14.100000,-1.800000,6.100000,13.200000